name: Redeploy
on: pull_request
env:
  GIGALIXIR_REMOTE: ${{ secrets.GIGALIXIR_REMOTE }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git checkout -B redeploy
          git push "${GIGALIXIR_REMOTE}" redeploy:master
