name: Redeploy
on:
  schedule:
    - cron: '0 6 1 * *'
env:
  GIGALIXIR_REMOTE: ${{ secrets.GIGALIXIR_REMOTE }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git checkout -B redeploy
          git -c user.name="gh action" -c user.email="dallin@kuali.co" commit --allow-empty -m "trigger re-deploy"
          git push -f "${GIGALIXIR_REMOTE}" redeploy:master
